apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 623234912973.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:47abb00c159d83c948bf029e9271dde8a483c2a7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: electronics-service
  labels:
    app: electronics
spec:
  type: ClusterIP
  selector:
    app: electronics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
