apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
  labels:
    app: sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
      - name: sports
        image: 623234912973.dkr.ecr.us-east-1.amazonaws.com/shopping-site-sports:47abb00c159d83c948bf029e9271dde8a483c2a7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sports-service
  labels:
    app: sports
spec:
  type: ClusterIP
  selector:
    app: sports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
